# Generated by Django 4.0.4 on 2022-06-30 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charterinsuarance', '0003_alter_transaction_txn_date_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 16, 14, 40, 99680), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employeeID',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
