# Generated by Django 4.0.4 on 2022-07-14 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charterinsuarance', '0006_alter_user_managers_alter_transaction_txn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_branch',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 14, 39, 33, 868077), editable=False, null=True),
        ),
    ]
