# Generated by Django 4.0.4 on 2022-07-14 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charterinsuarance', '0007_alter_branch_is_branch_alter_transaction_txn_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 14, 47, 46, 522722), editable=False, null=True),
        ),
    ]
