# Generated by Django 4.0.4 on 2022-07-14 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charterinsuarance', '0009_alter_branch_branch_code_alter_transaction_txn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 14, 54, 1, 421431), editable=False, null=True),
        ),
    ]
