# Generated by Django 4.0.4 on 2022-07-14 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charterinsuarance', '0010_alter_branch_branch_code_alter_transaction_txn_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branchcode',
        ),
        migrations.AddField(
            model_name='user',
            name='branchname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 15, 38, 47, 970854), editable=False, null=True),
        ),
    ]
