# Generated by Django 4.0.4 on 2022-07-14 09:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charterinsuarance', '0011_remove_user_branchcode_user_branchname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 15, 42, 30, 43514), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='branchname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charterinsuarance.branch'),
        ),
    ]
