# Generated by Django 4.0.4 on 2022-07-24 05:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charterinsuarance', '0012_alter_transaction_txn_date_alter_user_branchname'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='branchcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charterinsuarance.branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 11, 41, 53, 72671), editable=False, null=True),
        ),
    ]
