# Generated by Django 4.0.4 on 2022-07-24 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charterinsuarance', '0013_transaction_branchcode_alter_branch_branch_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='branchcode',
            new_name='branch',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 11, 42, 33, 460243), editable=False, null=True),
        ),
    ]
